/**
 * Build the wizard answers object used by generateTimeline and calculateLogistics.
 */
export function buildWizardAnswers(state) {
  const {
    date,
    photoEnabled,
    videoEnabled,
    photoStartHour,
    photoStartMinute,
    photoStartPeriod,
    photoCoverageHours,
    videoCoverageHours,
    wiz_ceremonyDuration,
    wiz_ceremonyHour,
    wiz_ceremonyMinute,
    wiz_ceremonyPeriod,
    wiz_receptionHour,
    wiz_receptionMinute,
    wiz_receptionPeriod,
    wiz_firstLookGroom,
    wiz_brideOkayBefore,
    wiz_grandEntrance,
    wiz_dinner,
    wiz_dinnerStartHour,
    wiz_dinnerStartMinute,
    wiz_dinnerStartPeriod,
    wiz_dinnerStyle,
    wiz_familyGroups,
    wiz_familyGroupNames,
    wiz_groomReadyAtCeremony,
    wiz_groomReadyAtReception,
    wiz_groomReadyAtBride,
    wiz_groomReadyAddress,
    wiz_ceremonyVenue,
    wiz_receptionSameAsCeremony,
    wiz_receptionVenue,
    wiz_receptionAddress,
    wiz_ceremonyAddress,
    wiz_brideReadyAddress,
    wiz_brideReadyStreet,
    wiz_brideReadyAtCeremony,
    wiz_brideReadyAtReception,
    wiz_groomReadyStreet,
    wiz_locations,
    wiz_firstLookParent,
    wiz_firstLookBridesmaids,
    wiz_firstLookOther,
    wiz_firstLookGroomLocation,
    wiz_firstLookParentLocation,
    wiz_firstLookBridesmaidsLocation,
    wiz_firstLookOtherLocation,
    wiz_drone,
    wiz_narration,
    wiz_portraitLocations,
    wiz_portraitSessions,
    wiz_distanceBetweenReady,
    wiz_distanceGroomToCeremony,
    wiz_distanceBrideToCeremony,
    wiz_distanceReceptionToCeremony,
    wiz_ceremonyOutdoor,
    wiz_cakeCutting,
    wiz_firstDance,
    wiz_brideParentDance,
    wiz_groomParentDance,
    wiz_specialDance,
    wiz_speeches,
    wiz_speechCount,
    wiz_openDanceFloor,
    wiz_garterToss,
    wiz_bouquetToss,
    wiz_preCeremonyBrideReady,
    wiz_preCeremonyPreDress,
    wiz_preCeremonyDetails,
    wiz_preCeremonyBrideParty,
    wiz_preCeremonyGroomReady,
    wiz_preCeremonyGroomParty,
    wiz_photoCoverageHours,
    wiz_videoCoverageHours,
    wiz_dinnerFlexibility,
    wiz_receptionStartFlexibility,
    wiz_appliedLogisticsSuggestions,
  } = state;

  return {
    date,
    photoEnabled,
    videoEnabled,
    photoStartHour,
    photoStartMinute,
    photoStartPeriod,
    photoCoverageHours: wiz_photoCoverageHours,
    videoCoverageHours: wiz_videoCoverageHours,
    ceremonyDuration: wiz_ceremonyDuration,
    ceremonyHour: wiz_ceremonyHour,
    ceremonyMinute: wiz_ceremonyMinute,
    ceremonyPeriod: wiz_ceremonyPeriod,
    receptionHour: wiz_receptionHour,
    receptionMinute: wiz_receptionMinute,
    receptionPeriod: wiz_receptionPeriod,
    firstLookGroom: wiz_firstLookGroom,
    brideOkayBefore: wiz_brideOkayBefore,
    grandEntrance: wiz_grandEntrance,
    dinner: wiz_dinner,
    dinnerStartHour: wiz_dinnerStartHour,
    dinnerStartMinute: wiz_dinnerStartMinute,
    dinnerStartPeriod: wiz_dinnerStartPeriod,
    dinnerStyle: wiz_dinnerStyle,
    familyGroups: wiz_familyGroups,
    familyGroupNames: wiz_familyGroupNames,
    groomReadyAtCeremony: wiz_groomReadyAtCeremony,
    groomReadyAtReception: wiz_groomReadyAtReception,
    groomReadyAtBride: wiz_groomReadyAtBride,
    groomReadyAddress: wiz_groomReadyAddress,
    ceremonyVenue: wiz_ceremonyVenue,
    receptionSameAsCeremony: wiz_receptionSameAsCeremony,
    receptionVenue: wiz_receptionVenue,
    receptionAddress: wiz_receptionAddress,
    ceremonyAddress: wiz_ceremonyAddress,
    brideReadyAddress: wiz_brideReadyAddress,
    brideReadyStreet: wiz_brideReadyStreet,
    brideReadyAtCeremony: wiz_brideReadyAtCeremony,
    brideReadyAtReception: wiz_brideReadyAtReception,
    groomReadyStreet: wiz_groomReadyStreet,
    locations: wiz_locations,
    portraitSessions: wiz_portraitSessions,
    firstLookParent: wiz_firstLookParent,
    firstLookBridesmaids: wiz_firstLookBridesmaids,
    firstLookOther: wiz_firstLookOther,
    firstLookGroomLocation: wiz_firstLookGroomLocation,
    firstLookParentLocation: wiz_firstLookParentLocation,
    firstLookBridesmaidsLocation: wiz_firstLookBridesmaidsLocation,
    firstLookOtherLocation: wiz_firstLookOtherLocation,
    drone: wiz_drone,
    narration: wiz_narration,
    portraitLocations: wiz_portraitLocations,
    distanceBetweenReady: wiz_distanceBetweenReady,
    distanceGroomToCeremony: wiz_distanceGroomToCeremony,
    distanceBrideToCeremony: wiz_distanceBrideToCeremony,
    distanceReceptionToCeremony: wiz_distanceReceptionToCeremony,
    ceremonyOutdoor: wiz_ceremonyOutdoor,
    cakeCutting: wiz_cakeCutting,
    firstDance: wiz_firstDance,
    brideParentDance: wiz_brideParentDance,
    groomParentDance: wiz_groomParentDance,
    specialDance: wiz_specialDance,
    speeches: wiz_speeches,
    speechCount: wiz_speechCount,
    openDanceFloor: wiz_openDanceFloor,
    garterToss: wiz_garterToss,
    bouquetToss: wiz_bouquetToss,
    preCeremonyBrideReady: wiz_preCeremonyBrideReady,
    preCeremonyPreDress: wiz_preCeremonyPreDress,
    preCeremonyDetails: wiz_preCeremonyDetails,
    preCeremonyBrideParty: wiz_preCeremonyBrideParty,
    preCeremonyGroomReady: wiz_preCeremonyGroomReady,
    preCeremonyGroomParty: wiz_preCeremonyGroomParty,
    dinnerFlexibility: wiz_dinnerFlexibility,
    receptionStartFlexibility: wiz_receptionStartFlexibility,
    appliedLogisticsSuggestions: wiz_appliedLogisticsSuggestions || [],
  };
}
